fix typo

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -88,16 +88,16 @@ jobs:
         env:
           USE_PYGEOS: 0
         run: |
-          pytest -v --cov=geopandas -r s -n auto --color=yes
+          pytest -v -r s -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
 
       - name: Test with PyGEOS
         shell: bash -l {0}
         continue-on-error: ${{ matrix.dev }}
-        if: env.HAS_PYGES == 'true'
+        if: env.HAS_PYGEOS == 1
         env:
           USE_PYGEOS: 1
         run: |
-          pytest -v --cov=geopandas -r s -n auto --color=yes
+          pytest -v -r s -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
 
       - name: Test with PostGIS
         shell: bash -l {0}
@@ -109,6 +109,6 @@ jobs:
         run: |
           conda install postgis -c conda-forge
           source ci/travis/setup_postgres.sh
-          pytest -v -r s --color=yes geopandas/io/tests/test_sql.py | tee /dev/stderr | if grep SKIPPED >/dev/null;then echo "TESTS SKIPPED, FAILING" && exit 1;fi
+          pytest -v -r s -color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/io/tests/test_sql.py | tee /dev/stderr | if grep SKIPPED >/dev/null;then echo "TESTS SKIPPED, FAILING" && exit 1;fi
 
       - uses: codecov/codecov-action@v1
