github actions run locally

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -15,66 +15,51 @@ concurrency:
 jobs:
   Linting:
     runs-on: ubuntu-latest
-
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-python@v4
       - uses: pre-commit/action@v3.0.0
 
+  prepenv:
+    runs-on: ubuntu-latest
+    outputs:
+      opts: ${{ steps.conda_env.outputs.opts }}
+      matrix: ${{ steps.conda_env.outputs.matrix }}
+    defaults:
+      run:
+        shell: bash -l {0}
+    steps:
+      - uses: actions/checkout@v3
+      - id: conda_env
+        run: |
+          python ci/scripts/env.py >> $GITHUB_OUTPUT
+
   Test:
-    needs: Linting
-    name: ${{ matrix.os }}, ${{ matrix.env }}
+    needs:
+      - Linting
+      - prepenv
+    name: ${{ matrix.os }}, ${{ matrix.env.name }}
     runs-on: ${{ matrix.os }}
     defaults:
       run:
         shell: bash -l {0}
     strategy:
       fail-fast: false
-      matrix:
-        os: [ubuntu-latest]
-        postgis: [false]
-        dev: [false]
-        env:
-          - ci/envs/38-minimal.yaml
-          - ci/envs/39-no-optional-deps.yaml
-          - ci/envs/38-pd11-defaults.yaml
-          - ci/envs/38-latest-defaults.yaml
-          - ci/envs/38-latest-conda-forge.yaml
-          - ci/envs/39-pd12-conda-forge.yaml
-          - ci/envs/39-latest-conda-forge.yaml
-          - ci/envs/310-latest-conda-forge.yaml
-          - ci/envs/311-latest-conda-forge.yaml
-        include:
-          - env: ci/envs/38-latest-conda-forge.yaml
-            os: macos-latest
-            postgis: false
-            dev: false
-          - env: ci/envs/39-latest-conda-forge.yaml
-            os: macos-latest
-            postgis: false
-            dev: false
-          - env: ci/envs/38-latest-conda-forge.yaml
-            os: windows-latest
-            postgis: false
-            dev: false
-          - env: ci/envs/39-latest-conda-forge.yaml
-            os: windows-latest
-            postgis: false
-            dev: false
-          - env: ci/envs/310-dev.yaml
-            os: ubuntu-latest
-            dev: true
+      if: ${{ env.ACT }}
+      max-parallel: 1  # mamba and caching in ACT.  still parallel on github?
+      matrix: ${{ fromJson(needs.prepenv.outputs.matrix) }}
 
     steps:
       - uses: actions/checkout@v3
-
       - name: Setup Conda
-        uses: conda-incubator/setup-miniconda@v2
+        uses: rraymondgh/setup-miniconda@main # waiting for https://github.com/conda-incubator/setup-miniconda/pull/265
         with:
-          environment-file: ${{ matrix.env }}
-          miniforge-version: latest
-          miniforge-variant: Mambaforge
+          environment-file: ${{ matrix.env.file }}
+          activate-environment: ${{ matrix.env.name }}
+          miniforge-version: ${{ fromJson(needs.prepenv.outputs.opts).miniforge-version }}
+          miniforge-variant: ${{ fromJson(needs.prepenv.outputs.opts).miniforge-varinat }}
           use-mamba: true
+          run-post: ${{ fromJson(needs.prepenv.outputs.opts).run-post }}
 
       - name: Check and Log Environment
         run: |
@@ -97,17 +82,19 @@ jobs:
         env:
           USE_PYGEOS: 0
         run: |
-          pytest -v -r a -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
+          [[ $ACT=="true" ]] && opts="-q" || opts="-v"
+          pytest $opts -r a -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
 
       - name: Test with PyGEOS
         if: env.HAS_PYGEOS == 1
         env:
           USE_PYGEOS: 1
         run: |
-          pytest -v -r a -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
+          [[ $ACT=="true" ]] && opts="-q" || opts="-v"
+          pytest $opts -r a -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
 
       - name: Test with PostGIS
-        if: contains(matrix.env, '39-pd12-conda-forge.yaml') && contains(matrix.os, 'ubuntu')
+        if: contains(matrix.env.file, '39-pd12-conda-forge.yaml') && contains(matrix.os, 'ubuntu')
         env:
           PGUSER: postgres
           PGPASSWORD: postgres
@@ -116,10 +103,11 @@ jobs:
         run: |
           conda install postgis -c conda-forge
           sh ci/scripts/setup_postgres.sh
-          pytest -v -r a --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/io/tests/test_sql.py | tee /dev/stderr | if grep SKIPPED >/dev/null;then echo "TESTS SKIPPED, FAILING" && exit 1;fi
+          [[ $ACT=="true" ]] && opts="-q" || opts="-v"
+          pytest $opts -r a --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/io/tests/test_sql.py | tee /dev/stderr | if grep SKIPPED >/dev/null;then echo "TESTS SKIPPED, FAILING" && exit 1;fi
 
       - name: Test docstrings
-        if: contains(matrix.env, '39-pd12-conda-forge.yaml') && contains(matrix.os, 'ubuntu')
+        if: contains(matrix.env.file, '39-pd12-conda-forge.yaml') && contains(matrix.os, 'ubuntu')
         env:
           USE_PYGEOS: 1
         run: |
