something dodgy with box

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -21,9 +21,54 @@ jobs:
       - uses: actions/setup-python@v4
       - uses: pre-commit/action@v3.0.0
 
+  prepenv:
+    runs-on: ubuntu-latest
+    outputs:
+      env: ${{ steps.conda_env.outputs.env }}
+    defaults:
+      run:
+        shell: bash -l {0}
+    steps:
+      - uses: actions/checkout@v3
+      - id: conda_env
+        run: |
+          # env=$( find ci/lock -name "*.lock" | jq -Rn '[inputs]' )
+          # echo $env > tmp
+          # # echo "::set-output name=env::$( cat tmp )" # this is deprecated way
+          # echo '::set-output name=env::[{"env": "ci/lock/39-no-optional-deps.lock", "env_name": "39-no-optional-deps.lock"}]'
+          # # echo '$env' >> $GITHUB_OUTPUT
+          python ci/scripts/env.py
+  Debug:
+    needs:
+      - prepenv
+    name: ${{ matrix.os }}, ${{ matrix.env.env }}
+    runs-on: ${{ matrix.os }}
+    defaults:
+      run:
+        shell: bash -l {0}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest]
+        env: ${{ fromJson( needs.prepenv.outputs.env ) }}
+
+    steps:
+      - uses: actions/checkout@v3
+      - name: a name
+        env:
+          SOME_DEBUG: ${{ endsWith(matrix.env.env, 'lock') }}
+        run: |
+          echo $SOME_DEBUG
+          python --version
+          python ci/scripts/env.py
+
+
+
   Test:
-    needs: Linting
-    name: ${{ matrix.os }}, ${{ matrix.env }}
+    needs:
+      # - Linting
+      - prepenv
+    name: ${{ matrix.os }}, ${{ matrix.env.env }}
     runs-on: ${{ matrix.os }}
     defaults:
       run:
@@ -34,36 +79,27 @@ jobs:
         os: [ubuntu-latest]
         postgis: [false]
         dev: [false]
-        env:
-          - ci/envs/38-minimal.yaml
-          - ci/envs/39-no-optional-deps.yaml
-          - ci/envs/38-pd11-defaults.yaml
-          - ci/envs/38-latest-defaults.yaml
-          - ci/envs/38-latest-conda-forge.yaml
-          - ci/envs/39-pd12-conda-forge.yaml
-          - ci/envs/39-latest-conda-forge.yaml
-          - ci/envs/310-latest-conda-forge.yaml
-          - ci/envs/311-latest-conda-forge.yaml
-        include:
-          - env: ci/envs/38-latest-conda-forge.yaml
-            os: macos-latest
-            postgis: false
-            dev: false
-          - env: ci/envs/39-latest-conda-forge.yaml
-            os: macos-latest
-            postgis: false
-            dev: false
-          - env: ci/envs/38-latest-conda-forge.yaml
-            os: windows-latest
-            postgis: false
-            dev: false
-          - env: ci/envs/39-latest-conda-forge.yaml
-            os: windows-latest
-            postgis: false
-            dev: false
-          - env: ci/envs/310-dev.yaml
-            os: ubuntu-latest
-            dev: true
+        env: ${{ fromJson( needs.prepenv.outputs.env ) }}
+        # include:
+        #   - env: ci/envs/38-latest-conda-forge.yaml
+        #     os: macos-latest
+        #     postgis: false
+        #     dev: false
+        #   - env: ci/envs/39-latest-conda-forge.yaml
+        #     os: macos-latest
+        #     postgis: false
+        #     dev: false
+        #   - env: ci/envs/38-latest-conda-forge.yaml
+        #     os: windows-latest
+        #     postgis: false
+        #     dev: false
+        #   - env: ci/envs/39-latest-conda-forge.yaml
+        #     os: windows-latest
+        #     postgis: false
+        #     dev: false
+        #   - env: ci/envs/310-dev.yaml
+        #     os: ubuntu-latest
+        #     dev: true
 
     steps:
       - uses: actions/checkout@v3
@@ -71,10 +107,13 @@ jobs:
       - name: Setup Conda
         uses: conda-incubator/setup-miniconda@v2
         with:
-          environment-file: ${{ matrix.env }}
-          miniforge-version: latest
-          miniforge-variant: Mambaforge
+          environment-file: ${{ matrix.env.env }}
+          # activate-environment: ${{ matrix.env }}
+          miniforge-version: ""
+          miniforge-variant: ""
           use-mamba: true
+          run-post: ${{ endsWith( matrix.env.env, "lock") }}
+          # run-post: false
 
       - name: Check and Log Environment
         run: |
@@ -97,17 +136,19 @@ jobs:
         env:
           USE_PYGEOS: 0
         run: |
-          pytest -v -r a -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
+          [[ $ACT=="true" ]] && opts="-q" || opts="-v"
+          pytest $opts -r a -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
 
       - name: Test with PyGEOS
         if: env.HAS_PYGEOS == 1
         env:
           USE_PYGEOS: 1
         run: |
-          pytest -v -r a -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
+          [[ $ACT=="true" ]] && opts="-q" || opts="-v"
+          pytest $opts -r a -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
 
       - name: Test with PostGIS
-        if: contains(matrix.env, '39-pd12-conda-forge.yaml') && contains(matrix.os, 'ubuntu')
+        if: contains(matrix.env.env, '39-pd12-conda-forge.yaml') && contains(matrix.os, 'ubuntu')
         env:
           PGUSER: postgres
           PGPASSWORD: postgres
@@ -116,10 +157,11 @@ jobs:
         run: |
           conda install postgis -c conda-forge
           sh ci/scripts/setup_postgres.sh
-          pytest -v -r a --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/io/tests/test_sql.py | tee /dev/stderr | if grep SKIPPED >/dev/null;then echo "TESTS SKIPPED, FAILING" && exit 1;fi
+          [[ $ACT=="true" ]] && opts="-q" || opts="-v"
+          pytest $opts -r a --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/io/tests/test_sql.py | tee /dev/stderr | if grep SKIPPED >/dev/null;then echo "TESTS SKIPPED, FAILING" && exit 1;fi
 
       - name: Test docstrings
-        if: contains(matrix.env, '39-pd12-conda-forge.yaml') && contains(matrix.os, 'ubuntu')
+        if: contains(matrix.env.env, '39-pd12-conda-forge.yaml') && contains(matrix.os, 'ubuntu')
         env:
           USE_PYGEOS: 1
         run: |
