test docstring with postgis only

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -58,7 +58,7 @@ jobs:
       - uses: actions/checkout@v2
 
       - name: Setup Conda
-        uses: s-weigand/setup-conda@v1.0.4
+        uses: s-weigand/setup-conda@v1.0.5
         with:
           activate-conda: false
 
@@ -93,7 +93,7 @@ jobs:
           USE_PYGEOS: 0
         run: |
           source activate test
-          pytest -v -r s -n auto --doctest-modules --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
+          pytest -v -r s -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
 
       - name: Test with PyGEOS
         shell: bash
@@ -103,7 +103,7 @@ jobs:
           USE_PYGEOS: 1
         run: |
           source activate test
-          pytest -v -r s -n auto --doctest-modules --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
+          pytest -v -r s -n auto --color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/
 
       - name: Test with PostGIS
         shell: bash
@@ -116,6 +116,6 @@ jobs:
           source activate test
           conda install postgis -c conda-forge
           source ci/travis/setup_postgres.sh
-          pytest -v -r s -color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/io/tests/test_sql.py | tee /dev/stderr | if grep SKIPPED >/dev/null;then echo "TESTS SKIPPED, FAILING" && exit 1;fi
+          pytest -v -r s --doctest-modules -color=yes --cov=geopandas --cov-append --cov-report term-missing --cov-report xml geopandas/io/tests/test_sql.py | tee /dev/stderr | if grep SKIPPED >/dev/null;then echo "TESTS SKIPPED, FAILING" && exit 1;fi
 
       - uses: codecov/codecov-action@v1
