Add color, test failure modes, simplify

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -17,35 +17,33 @@ jobs:
 
   Test:
     needs: Linting
-    name: Run Tests ${{ matrix.os }} / ENV=${{ matrix.env }} / POSTGIS=${{ matrix.postgis }} / DEV=${{ matrix.dev }}
+    name: ${{ matrix.os }}, ${{ matrix.env }}, POSTGIS=${{ matrix.postgis }}
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         os: [ubuntu-latest]
         postgis: [false]
         dev: [false]
-        experimental: [false]
         env:
           - ci/travis/36-minimal.yaml
-          - ci/travis/37-dev.yaml
           - ci/travis/38-no-optional-deps.yaml
           - ci/travis/36-pd025.yaml
           - ci/travis/37-latest-conda-forge.yaml
           - ci/travis/38-latest-conda-forge.yaml
         include:
-          - env: ci/travis/38-latest-conda-forge.yaml
+          - env: ci/travis/37-latest-conda-forge.yaml
             os: macos-latest
             postgis: false
             dev: false
           - env: ci/travis/38-latest-conda-forge.yaml
+            os: macos-latest
+            postgis: false
+            dev: false
+          - env: ci/travis/37-latest-conda-forge.yaml
             os: windows-latest
             postgis: false
             dev: false
-          - env: ci/travis/37-latest-conda-forge.yaml
-            os: macos-latest
-            postgis: false
-            dev: false
-          - env: ci/travis/37-latest-conda-forge.yaml
+          - env: ci/travis/38-latest-conda-forge.yaml
             os: windows-latest
             postgis: false
             dev: false
@@ -53,7 +51,7 @@ jobs:
             os: ubuntu-latest
             postgis: true
             dev: false
-          - env: ci/travis/38-latest-conda-forge.yaml
+          - env: ci/travis/37-dev.yaml
             os: ubuntu-latest
             postgis: false
             dev: true
@@ -70,8 +68,9 @@ jobs:
           path: ~/conda_pkgs_dir
           key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles(matrix.env) }}-${{ matrix.postgis }}-${{ matrix.dev }}
       
-      - uses: actions/setup-python@v2
-      
+      - name: Set up base Python
+        uses: actions/setup-python@v2
+
       - name: Get Pip Cache Dir
         shell: bash
         run: |
@@ -102,23 +101,17 @@ jobs:
         shell: bash -l {0}
         if: matrix.dev == true
         run: |
+          conda remove pandas
+          conda remove matplotlib
+          conda remove shapely
           pip install -U git+https://github.com/pydata/pandas.git@master
           pip install -U git+https://github.com/matplotlib/matplotlib.git@master
           pip install -U git+https://github.com/Toblerity/Shapely.git@master
 
-      - name: Install & Setup PostgreSQL
-        if: matrix.postgis == true
-        shell: bash -l {0}
-        run: |
-          conda install postgis -c conda-forge
-          PGUSER=postgres
-          PGPASSWORD=postgres
-          source ci/travis/setup_postgres.sh
-
       - name: Check and Log Environment
         shell: bash -l {0}
         run: |
-          if ( $(conda list | grep -q pygeos) || $(pip freeze | grep -q pygeos) )
+          if ( { conda list & pip freeze; } | grep -q pygeos  )
           then
             echo "Setting HAS_PYGEOS=1"
             echo '::set-env name=HAS_PYGEOS::1'
@@ -129,39 +122,31 @@ jobs:
           conda info
           conda list
 
-      - name: Test PostGIS
-        shell: bash -l {0}
-        if: matrix.postgis == true
-        env:
-          PGUSER: postgres
-          PGPASSWORD: postgres
-        run: pytest -v -k "postgis" || if grep -q SKIPPED;then exit 1;fi
-
       - name: Test without PyGEOS
         shell: bash -l {0}
         continue-on-error: ${{ matrix.dev }}
         env:
           USE_PYGEOS: 0
-        run: |
-          if ${{ matrix.dev }} != true
-          then
-            pytest -v --cov=geopandas --cov-report xml -r s --numprocesses=auto || (echo "RUN FAILED, RUNNING SEQUENTIALLY FOR DEBUGGING" && pytest -v -r s && exit 1)
-          else
-            pytest -v -r s
-          fi
+        run: pytest -v --cov=geopandas -r s -n auto --color=yes
 
       - name: Test with PyGEOS
         shell: bash -l {0}
         continue-on-error: ${{ matrix.dev }}
-        if: env.HAS_PYGEOS == 1
+        if: env.HAS_PYGES == 'true'
         env:
           USE_PYGEOS: 1
+        run: pytest -v --cov=geopandas -r s -n auto --color=yes
+
+      - name: Test with PostGIS
+        shell: bash -l {0}
+        if: matrix.postgis == true
+        env:
+          PGUSER: postgres
+          PGPASSWORD: postgres
+          PGHOST: "127.0.0.1"
         run: |
-          if ${{ matrix.dev }} != true
-          then
-            pytest -v --cov=geopandas --cov-report xml -r s --numprocesses=auto || (echo "RUN FAILED, RUNNING SEQUENTIALLY FOR DEBUGGING" && pytest -v -r s && exit 1)
-          else
-            pytest -v -r s
-          fi
+          conda install postgis -c conda-forge
+          source ci/travis/setup_postgres.sh
+          pytest -v -k "postgis" -r s --color=yes | tee /dev/stderr | if grep SKIPPED >/dev/null;then echo "TESTS SKIPPED, FAILING" && exit 1;fi
 
       - uses: codecov/codecov-action@v1
